# Generated by Django 6.0.5 on 2026-05-21 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Godown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('state_code', models.CharField(default='32', help_text='Kerala=32', max_length=2)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('invoice_prefix', models.CharField(default='SL', max_length=10)),
                ('po_prefix', models.CharField(default='PO', max_length=10)),
                ('grn_prefix', models.CharField(default='GRN', max_length=10)),
                ('invoice_note', models.TextField(blank=True, default='Goods once sold will not be taken back.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rent', 'Godown Rent'), ('forklift', 'Forklift Rent'), ('labour', 'Labour / Loading'), ('transport', 'Transport / Freight'), ('electricity', 'Electricity'), ('misc', 'Miscellaneous')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=300)),
                ('paid_to', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('online', 'Online')], default='cash', max_length=10)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], default='paid', max_length=10)),
                ('bill_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='godown.godown')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('state', models.CharField(default='Kerala', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='godown.godown')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('thickness', models.CharField(choices=[('0.5mm', '0.5mm'), ('0.6mm', '0.6mm'), ('0.8mm', '0.8mm'), ('1.0mm', '1.0mm'), ('1.2mm', '1.2mm')], default='0.6mm', max_length=10)),
                ('cut_type', models.CharField(choices=[('Flat Cut', 'Flat Cut'), ('Quarter Cut', 'Quarter Cut'), ('Rift Cut', 'Rift Cut'), ('Rotary Cut', 'Rotary Cut')], default='Flat Cut', max_length=20)),
                ('finish', models.CharField(choices=[('Natural', 'Natural'), ('Dyed', 'Dyed'), ('Backed (Paper)', 'Backed (Paper)'), ('Backed (Fabric)', 'Backed (Fabric)')], default='Natural', max_length=20)),
                ('buy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('min_stock', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('hsn_code', models.CharField(blank=True, default='4408', max_length=20)),
                ('stock_qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sheet_length', models.DecimalField(decimal_places=2, default=8, max_digits=6)),
                ('sheet_width', models.DecimalField(decimal_places=2, default=4, max_digits=6)),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='godown.godown')),
            ],
            options={
                'ordering': ['species', 'thickness'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Received'), ('received', 'Fully Received'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('advance_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_mode', models.CharField(blank=True, choices=[('credit', 'Credit'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='bank', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='godown.godown')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_sqft', models.DecimalField(decimal_places=4, help_text='Always in sqft — canonical unit', max_digits=10)),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_unit', models.CharField(choices=[('sqft', 'Square Feet'), ('pcs', 'Pieces')], default='sqft', max_length=5)),
                ('pieces', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sheet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sheet_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_items', to='godown.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='godown.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('transport', models.CharField(blank=True, max_length=100)),
                ('po_reference', models.CharField(blank=True, max_length=50)),
                ('delivery_address', models.TextField(blank=True)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='credit', max_length=10)),
                ('is_igst', models.BooleanField(default=False)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='godown.customer')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='godown.godown')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('godown', 'bill_number')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer / NEFT'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('rtgs', 'RTGS'), ('neft', 'NEFT')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='godown.sale')),
            ],
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lead_days', models.PositiveSmallIntegerField(default=14)),
                ('avg_daily_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='godown.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=30)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_number', models.CharField(blank=True, max_length=50)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(choices=[('credit', 'Credit'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('upi', 'UPI')], default='credit', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ins', to='godown.godown')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grns', to='godown.purchaseorder')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=30)),
                ('qty_sqft', models.DecimalField(decimal_places=4, max_digits=10)),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_at_sale', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='godown.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='godown.sale')),
                ('grn_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_items', to='godown.stockin')),
            ],
        ),
        migrations.CreateModel(
            name='LandingExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('labour', 'Labour / Loading'), ('forklift', 'Forklift Charges'), ('customs', 'Customs / Duty'), ('insurance', 'Insurance'), ('misc', 'Miscellaneous')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_to', models.CharField(blank=True, max_length=100)),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_expenses', to='godown.stockin')),
            ],
        ),
        migrations.CreateModel(
            name='StockInItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_location', models.CharField(blank=True, max_length=20)),
                ('qty_sqft', models.DecimalField(decimal_places=4, help_text='Always in sqft', max_digits=10)),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('landed_rate', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('qty_unit', models.CharField(choices=[('sqft', 'Square Feet'), ('pcs', 'Pieces')], default='sqft', max_length=5)),
                ('pieces', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sheet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sheet_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='godown.product')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='godown.stockin')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('gst_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('species_supplied', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='godown.godown')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockin',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='godown.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos', to='godown.supplier'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('limited', 'Limited User')], default='limited', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='godown.godown')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GodownSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_type', models.CharField(choices=[('sale', 'Sale'), ('po', 'Purchase Order'), ('grn', 'GRN')], max_length=10)),
                ('last_num', models.PositiveIntegerField(default=0)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='godown.godown')),
            ],
            options={
                'unique_together': {('godown', 'seq_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='stockin',
            unique_together={('godown', 'grn_number')},
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('godown', 'po_number')},
        ),
    ]
