# Generated by Django 6.0.5 on 2026-05-22 04:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_number', models.CharField(max_length=30)),
                ('customer_name', models.CharField(blank=True, help_text='Free text if no customer record', max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('include_gst', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimations', to='godown.customer')),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimations', to='godown.godown')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('godown', 'est_number')},
            },
        ),
        migrations.CreateModel(
            name='EstimationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('qty_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate_per_sqft', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pieces', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sheet_length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sheet_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('estimation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='est_items', to='godown.estimation')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='godown.product')),
            ],
        ),
    ]
