# Generated by Django 6.0.5 on 2026-05-26 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0002_estimation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='godownsequence',
            name='seq_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('po', 'Purchase Order'), ('grn', 'GRN'), ('est', 'Estimation')], max_length=10),
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('thickness', 'Product Thickness'), ('cut_type', 'Cut Type'), ('finish', 'Finish'), ('expense_category', 'Expense Category'), ('landing_expense_category', 'Landing Expense Category')], max_length=30)),
                ('value', models.CharField(help_text='The stored value (e.g. 0.6mm)', max_length=100)),
                ('label', models.CharField(help_text='Display label (e.g. 0.6mm Thin)', max_length=100)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected in forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookup_values', to='godown.godown')),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
                'unique_together': {('godown', 'category', 'value')},
            },
        ),
    ]
