# Generated by Django 6.0.5 on 2026-06-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0003_lookup_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='advance_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Exchange rate at time of advance (USD→INR). 1 if INR.', max_digits=10),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)')], default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='stockin',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1, help_text='Exchange rate at time of this payment (USD→INR). 1 if INR.', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockin',
            name='payment_currency',
            field=models.CharField(choices=[('INR', 'Indian Rupee (₹)'), ('USD', 'US Dollar ($)')], default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='advance_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in original currency (INR or USD)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockin',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount in payment currency', max_digits=12),
        ),
    ]
