# Generated by Django 6.0.5 on 2026-06-12 10:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0004_currency_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('transit', 'Transit Damage'), ('quality', 'Quality Reject'), ('moisture', 'Moisture / Warping'), ('handling', 'Handling Damage'), ('fire', 'Fire / Flood'), ('other', 'Other')], default='other', max_length=20)),
                ('qty_sqft', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cost_rate', models.DecimalField(decimal_places=4, default=0, help_text='Cost per sqft at time of damage (auto-filled from product avg cost)', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='godown.godown')),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='damages', to='godown.stockin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='damages', to='godown.product')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
