# Generated by Django 6.0.6 on 2026-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0005_stock_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin',
            field=models.CharField(blank=True, help_text='Buyer GSTIN — required for e-invoice', max_length=15),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, help_text='Buyer pincode — required for e-Way Bill', max_length=6),
        ),
        migrations.AddField(
            model_name='customer',
            name='place_of_supply',
            field=models.CharField(blank=True, help_text='Place of supply state code for GST', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='state_code',
            field=models.CharField(blank=True, help_text='2-digit state code e.g. 32 for Kerala', max_length=2),
        ),
        migrations.AddField(
            model_name='godown',
            name='cin_number',
            field=models.CharField(blank=True, help_text='Company Identification Number (if applicable)', max_length=21),
        ),
        migrations.AddField(
            model_name='godown',
            name='gsp_client_id',
            field=models.CharField(blank=True, help_text='GSP Client ID for API auth', max_length=100),
        ),
        migrations.AddField(
            model_name='godown',
            name='gsp_client_secret',
            field=models.CharField(blank=True, help_text='GSP Client Secret (stored encrypted in production)', max_length=200),
        ),
        migrations.AddField(
            model_name='godown',
            name='gsp_sandbox',
            field=models.BooleanField(default=True, help_text='Use sandbox/test API endpoint'),
        ),
        migrations.AddField(
            model_name='godown',
            name='gsp_username',
            field=models.CharField(blank=True, help_text='GSP API username (e.g. Masters India / IRIS)', max_length=100),
        ),
        migrations.AddField(
            model_name='godown',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
