# Generated by Django 6.0.6 on 2026-06-20 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0006_gsp_readiness_sale_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(blank=True, default='SQF', help_text='Unit of measure for GSP (SQF=square feet)', max_length=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='ack_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatch_addr1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatch_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatch_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='dispatch_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sale',
            name='eway_bill_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='eway_bill_number',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='eway_bill_valid_upto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='irn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='sale',
            name='irn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='qr_code_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('bill', 'Tax Invoice'), ('cash_memo', 'Cash Memo (No Bill)')], default='bill', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='ship_addr1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='ship_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='ship_pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='sale',
            name='ship_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_distance',
            field=models.PositiveIntegerField(blank=True, help_text='Distance in KM', null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('1', 'Road'), ('2', 'Rail'), ('3', 'Air'), ('4', 'Ship')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='sale',
            name='transporter_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='sale',
            name='transporter_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='4408', help_text='HSN code for e-invoice (face veneer = 4408)', max_length=8),
        ),
    ]
