# Generated by Django 6.0.6 on 2026-06-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0010_fix_decimal_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=4, default=500, help_text='Minimum stock level in sq.m', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='uom',
            field=models.CharField(blank=True, default='SQF', help_text='Unit of measure for GSP/e-invoice (SQF = square feet, internal unit)', max_length=5),
        ),
        migrations.AlterField(
            model_name='stockinitem',
            name='qty_unit',
            field=models.CharField(choices=[('sqft', 'Square Feet'), ('pcs', 'Pieces')], default='sqm', max_length=5),
        ),
    ]
