# Generated by Django 6.0.6 on 2026-06-25 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0011_field_cleanups_final'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(help_text='e.g. SBI Current A/c, HDFC Savings', max_length=100)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('ifsc', models.CharField(blank=True, max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('account_type', models.CharField(choices=[('savings', 'Savings Account'), ('current', 'Current Account'), ('cc', 'Cash Credit'), ('od', 'Overdraft'), ('wallet', 'Digital Wallet / UPI')], default='current', max_length=10)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Opening balance when account was added to system', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='godown.godown')),
            ],
            options={
                'ordering': ['account_name'],
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('txn_type', models.CharField(choices=[('credit', 'Credit (Money In)'), ('debit', 'Debit (Money Out)')], max_length=10)),
                ('category', models.CharField(choices=[('sale_receipt', 'Sale Receipt'), ('supplier_payment', 'Supplier Payment'), ('expense', 'Expense'), ('advance_paid', 'Advance Paid'), ('advance_received', 'Advance Received'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('opening', 'Opening Balance'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, help_text='UTR / cheque number / reference', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='godown.bankaccount')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_txns', to='godown.expense')),
                ('grn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_txns', to='godown.stockin')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_txns', to='godown.sale')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
