# Generated by Django 6.0.6 on 2026-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0013_sale_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_name',
            field=models.CharField(blank=True, help_text='Name shown to customers when selling. Leave blank to use the purchase name (species).', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(help_text='Purchase / internal name', max_length=100),
        ),
    ]
