# Generated by Django 6.0.6 on 2026-06-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0015_backfill_sale_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_name',
            field=models.CharField(help_text='Name shown to customers when selling. Defaults to the purchase name but must be set.', max_length=100),
        ),
    ]
