# Generated by Django 6.0.6 on 2026-06-30 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0016_sale_name_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingexpense',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='landingexpense',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Service vendor this charge is owed to — creates a running payable for them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='landing_expenses', to='godown.supplier'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier_type',
            field=models.CharField(choices=[('material', 'Material Supplier'), ('service', 'Service Vendor (transport, forklift, labour, etc.)'), ('both', 'Both — Material & Service')], default='material', help_text='Material suppliers sell veneer stock. Service vendors provide transport, forklift, labour etc.', max_length=10),
        ),
        migrations.AlterField(
            model_name='landingexpense',
            name='paid_to',
            field=models.CharField(blank=True, help_text='Free-text name — kept for backward compatibility / quick entry without a vendor record.', max_length=100),
        ),
    ]
