# Generated by Django 6.0.6 on 2026-07-03 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0019_backfill_vendor_payments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='godownsequence',
            name='seq_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('po', 'Purchase Order'), ('grn', 'GRN'), ('est', 'Estimation'), ('grn_expense', 'GRN Expense')], max_length=15),
        ),
        migrations.CreateModel(
            name='GRNExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_number', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('transport', 'Transportation'), ('labour', 'Labour / Loading'), ('forklift', 'Forklift Charges'), ('customs', 'Customs / Duty'), ('insurance', 'Insurance'), ('misc', 'Miscellaneous')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('godown', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_expenses', to='godown.godown')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_expenses', to='godown.stockin')),
                ('vendor', models.ForeignKey(blank=True, help_text='Service vendor — creates a running payable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_expenses', to='godown.supplier')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
