# Generated by Django 6.0.7 on 2026-07-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0022_cleanup_landing_expenses'),
    ]

    operations = [
        migrations.AddField(
            model_name='grnexpense',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST amount — auto-calculated from base × rate, editable', max_digits=10),
        ),
        migrations.AddField(
            model_name='grnexpense',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % on this expense (0 if vendor is unregistered or exempt)', max_digits=5),
        ),
        migrations.AddField(
            model_name='stockin',
            name='customs_duty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Basic Customs Duty (BCD) paid at port of entry', max_digits=10),
        ),
        migrations.AddField(
            model_name='stockin',
            name='igst_import',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IGST paid at customs on import — added to landed cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='grnexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Base amount before GST', max_digits=10),
        ),
    ]
