# Generated by Django 6.0.7 on 2026-07-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0023_gst_import_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockin',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST amount on material — auto-calculated, editable. Part of supplier payable but NOT landed cost (ITC claimable)', max_digits=12),
        ),
        migrations.AddField(
            model_name='stockin',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='GST % on material purchase (0 for imports — use igst_import instead)', max_digits=5),
        ),
    ]
