# Generated by Django 6.0.7 on 2026-08-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0024_grn_material_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, default='4408', help_text='HSN code — up to 15 characters including dots (e.g. 4408, 44.08, 4408.10.10)', max_length=15),
        ),
    ]
