# Generated by Django 4.2.30 on 2026-08-18 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godown', '0026_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling rate per sq.m — optional at creation, set before first sale', max_digits=10),
        ),
    ]
